name: deployers

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deployer-frontend
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
