import { MenuCard } from './types';

export const menuCards: MenuCard[] = [
  { id: 'frontend', type: 'frontend', label: 'Frontend', icon: '🌐', color: '#3b82f6' },
  { id: 'backend', type: 'backend', label: 'Backend', icon: '⚙️', color: '#10b981' },
  { id: 'database', type: 'database', label: 'Database', icon: '🗄️', color: '#FFD700' },
  { id: 'repository', type: 'repository', label: 'Repository', icon: '📦', color: '#6366f1' },
  { id: 'cicd', type: 'cicd', label: 'CI/CD', icon: '🔄', color: '#f59e0b' },
  { id: 'server', type: 'server', label: 'Server', icon: '🖥️', color: '#ef4444' },
];

export const componentFrameworks = {
  frontend: [
    { value: 'react', label: 'React' },
    { value: 'nextjs', label: 'Next.js' },
    { value: 'vue', label: 'Vue.js' },
    { value: 'angular', label: 'Angular' },
    { value: 'svelte', label: 'Svelte' },
  ],
  backend: [
    { value: 'nodejs', label: 'Node.js' },
    { value: 'nestjs', label: 'NestJS' },
    { value: 'express', label: 'Express' },
    { value: 'fastify', label: 'Fastify' },
    { value: 'python', label: 'Python' },
    { value: 'django', label: 'Django' },
    { value: 'flask', label: 'Flask' },
  ],
  database: [
    { value: 'postgresql', label: 'PostgreSQL' },
    { value: 'mysql', label: 'MySQL' },
    { value: 'mongodb', label: 'MongoDB' },
    { value: 'redis', label: 'Redis' },
    { value: 'sqlite', label: 'SQLite' },
    { value: 'mariadb', label: 'MariaDB' },
    { value: 'elasticsearch', label: 'Elasticsearch' },
  ],
  devops: [
    { value: 'docker', label: 'Docker' },
    { value: 'kubernetes', label: 'Kubernetes' },
    { value: 'terraform', label: 'Terraform' },
    { value: 'ansible', label: 'Ansible' },
    { value: 'helm', label: 'Helm' },
    { value: 'github-actions', label: 'GitHub Actions' },
    { value: 'gitlab-ci', label: 'GitLab CI' },
    { value: 'jenkins', label: 'Jenkins' },
    { value: 'circleci', label: 'CircleCI' },
    { value: 'azure-devops', label: 'Azure DevOps' },
  ],
  repository: [
    { value: 'github', label: 'GitHub' },
    { value: 'gitlab', label: 'GitLab' },
    { value: 'bitbucket', label: 'Bitbucket' },
    { value: 'azure-devops', label: 'Azure DevOps' },
  ],
  cicd: [
    { value: 'github-actions', label: 'GitHub Actions' },
    { value: 'gitlab-ci', label: 'GitLab CI' },
    { value: 'jenkins', label: 'Jenkins' },
    { value: 'circleci', label: 'CircleCI' },
    { value: 'azure-pipelines', label: 'Azure Pipelines' },
    { value: 'aws-codebuild', label: 'AWS CodeBuild' },
  ],
  server: [
    { value: 'aws', label: 'AWS' },
    { value: 'gcp', label: 'Google Cloud (Coming Soon)', disabled: true },
    { value: 'azure', label: 'Azure (Coming Soon)', disabled: true },
    { value: 'digitalocean', label: 'DigitalOcean (Coming Soon)', disabled: true },
    { value: 'vercel', label: 'Vercel (Coming Soon)', disabled: true },
    { value: 'netlify', label: 'Netlify (Coming Soon)', disabled: true },
  ],
        optional: [
          { value: 'unit-testing', label: 'Unit Testing' },
          { value: 'husky', label: 'Husky' },
          { value: 'eslint', label: 'ESLint' },
          { value: 'prettier', label: 'Prettier' },
          { value: 'vitest', label: 'Vitest' },
          { value: 'sentry', label: 'Sentry' },
        ],
        comingSoon: [
          { value: 'sonarqube', label: 'SonarQube' },
          { value: 'storybook', label: 'Storybook' },
          { value: 'cypress', label: 'Cypress' },
          { value: 'playwright', label: 'Playwright' },
          { value: 'bundle-analyzer', label: 'Bundle Analyzer' },
          { value: 'datadog', label: 'Datadog' },
          { value: 'lighthouse', label: 'Lighthouse' },
          { value: 'newrelic', label: 'New Relic' },
        ],
};
